# Generated by Django 5.2.6 on 2025-09-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userreview_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestListExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(blank=True, default=list)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('methodology', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best_list_extra', to='main.article')),
            ],
        ),
    ]
