# Generated by Django 5.2.6 on 2025-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_setting_options_setting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
