# Generated by Django 5.2.6 on 2025-09-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-recorded_at'], 'verbose_name_plural': 'Price Histories'},
        ),
        migrations.RemoveIndex(
            model_name='pricehistory',
            name='main_priceh_product_f73953_idx',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
