# Generated by Django 5.1.7 on 2025-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_monthlyanalytics_articleview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleview',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleview',
            name='user',
        ),
        migrations.DeleteModel(
            name='MonthlyAnalytics',
        ),
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='ArticleView',
        ),
    ]
