# Generated by Django 5.1.7 on 2025-09-28 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_articleview_article_remove_articleview_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('affiliate_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_affiliateclick',
                'indexes': [models.Index(fields=['product'], name='main_affili_product_ff4000_idx'), models.Index(fields=['created_at'], name='main_affili_created_836bd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=50)),
                ('page_id', models.PositiveIntegerField()),
                ('page_slug', models.SlugField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_pageview',
                'indexes': [models.Index(fields=['page_type', 'page_id'], name='main_pagevi_page_ty_11fcad_idx'), models.Index(fields=['created_at'], name='main_pagevi_created_23f12f_idx')],
            },
        ),
    ]
