# Generated by Django 5.2.6 on 2025-09-28 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_affiliateclick_pageview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliateclick',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='affiliateclick',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_clicks', to='main.product'),
        ),
        migrations.AlterField(
            model_name='affiliateclick',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliateclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affiliateclick',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='affiliateclick',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pageview',
            table=None,
        ),
        migrations.CreateModel(
            name='MonthlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_views', models.IntegerField(default=0)),
                ('total_affiliate_clicks', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
