# Generated by Django 5.2.6 on 2025-09-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_affiliateclick_options_alter_pageview_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateclick',
            name='product',
        ),
        migrations.RemoveField(
            model_name='affiliateclick',
            name='user',
        ),
        migrations.DeleteModel(
            name='MonthlyAnalytics',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='user',
        ),
        migrations.DeleteModel(
            name='AffiliateClick',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
