# Generated by Django 5.1.7 on 2025-09-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
