# Generated by Django 5.1.7 on 2025-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_is_file_to_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
    ]
