# Generated by Django 5.1.7 on 2025-09-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_user_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('EDITOR', 'Editor'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='MEMBER', max_length=20),
        ),
    ]
