# Generated by Django 5.1.7 on 2025-09-29 19:10

from django.db import migrations


def update_user_roles(apps, schema_editor):
    """Update VISITOR and AUTHOR users to MEMBER role"""
    User = apps.get_model('main', 'User')
    User.objects.filter(role__in=['VISITOR', 'AUTHOR']).update(role='MEMBER')


def reverse_update_user_roles(apps, schema_editor):
    """Reverse migration - convert MEMBER back to VISITOR"""
    User = apps.get_model('main', 'User')
    User.objects.filter(role='MEMBER').update(role='VISITOR')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(update_user_roles, reverse_update_user_roles),
    ]
