# Generated by Django 5.2.6 on 2025-09-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_newslettersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
